# Generated by Django 5.0.6 on 2024-05-23 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='ProceedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='Версия нейроки')),
                ('video', models.FileField(upload_to='proceed-videos/')),
                ('original_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.originalvideo')),
            ],
        ),
        migrations.CreateModel(
            name='TimeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=128)),
                ('time_in_seconds', models.IntegerField()),
                ('proceed_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.proceedvideo')),
            ],
        ),
    ]
