# Generated by Django 5.0.6 on 2024-05-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceedvideo',
            name='title',
            field=models.CharField(default='Procceedd', max_length=100),
        ),
    ]
