# Generated by Django 5.0.6 on 2024-05-31 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0003_proceedvideo_excel_file_alter_proceedvideo_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proceedvideo",
            name="video",
            field=models.FileField(blank=True, upload_to="proceed-videos/"),
        ),
    ]
