# Generated by Django 5.0.6 on 2024-06-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0004_alter_proceedvideo_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="proceedvideo",
            name="pdf_file",
            field=models.FileField(blank=True, upload_to="pdf/"),
        ),
    ]
